import { Expense, ExpenseCategory } from '@/types/expense';

export type ExportFormat = 'csv' | 'json' | 'pdf';

export interface ExportOptions {
  format: ExportFormat;
  filename: string;
  startDate?: string;
  endDate?: string;
  categories?: ExpenseCategory[];
}

export interface ExportResult {
  success: boolean;
  message: string;
  recordCount: number;
}

// Filter expenses based on criteria
export const filterExpenses = (
  expenses: Expense[],
  startDate?: string,
  endDate?: string,
  categories?: ExpenseCategory[]
): Expense[] => {
  return expenses.filter(expense => {
    // Date filtering
    if (startDate && expense.date < startDate) return false;
    if (endDate && expense.date > endDate) return false;
    
    // Category filtering
    if (categories && categories.length > 0 && !categories.includes(expense.category)) {
      return false;
    }
    
    return true;
  });
};

// Generate CSV content
const generateCSV = (expenses: Expense[]): string => {
  const headers = ['Date', 'Category', 'Amount', 'Description'];
  const rows = expenses.map(expense => [
    expense.date,
    expense.category,
    expense.amount.toString(),
    `"${expense.description.replace(/"/g, '""')}"`
  ]);
  
  return [headers.join(','), ...rows.map(row => row.join(','))].join('\n');
};

// Generate JSON content  
const generateJSON = (expenses: Expense[]): string => {
  const exportData = {
    exportDate: new Date().toISOString(),
    recordCount: expenses.length,
    totalAmount: expenses.reduce((sum, expense) => sum + expense.amount, 0),
    expenses: expenses.map(expense => ({
      date: expense.date,
      category: expense.category,
      amount: expense.amount,
      description: expense.description
    }))
  };
  
  return JSON.stringify(exportData, null, 2);
};

// Generate PDF content (simple HTML approach)
const generatePDF = (expenses: Expense[]): string => {
  const totalAmount = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  
  const html = `
<!DOCTYPE html>
<html>
<head>
    <title>Expense Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .summary { background: #f5f5f5; padding: 15px; margin-bottom: 20px; border-radius: 5px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .amount { text-align: right; }
        .footer { margin-top: 30px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Expense Report</h1>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    
    <div class="summary">
        <strong>Summary:</strong> ${expenses.length} expenses totaling $${totalAmount.toFixed(2)}
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Description</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            ${expenses.map(expense => `
                <tr>
                    <td>${expense.date}</td>
                    <td>${expense.category}</td>
                    <td>${expense.description}</td>
                    <td class="amount">$${expense.amount.toFixed(2)}</td>
                </tr>
            `).join('')}
        </tbody>
    </table>
    
    <div class="footer">
        <p>This report was generated by Expense Tracker AI</p>
    </div>
</body>
</html>`;
  
  return html;
};

// Download file
const downloadFile = (content: string, filename: string, mimeType: string): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  
  link.href = url;
  link.download = filename;
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
};

// Main export function
export const exportExpenses = async (
  expenses: Expense[],
  options: ExportOptions
): Promise<ExportResult> => {
  try {
    // Filter expenses
    const filteredExpenses = filterExpenses(
      expenses,
      options.startDate,
      options.endDate,
      options.categories
    );
    
    if (filteredExpenses.length === 0) {
      return {
        success: false,
        message: 'No expenses match the selected criteria',
        recordCount: 0
      };
    }
    
    // Add artificial delay for loading state
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    let content: string;
    let mimeType: string;
    let fileExtension: string;
    
    switch (options.format) {
      case 'csv':
        content = generateCSV(filteredExpenses);
        mimeType = 'text/csv;charset=utf-8;';
        fileExtension = 'csv';
        break;
        
      case 'json':
        content = generateJSON(filteredExpenses);
        mimeType = 'application/json;charset=utf-8;';
        fileExtension = 'json';
        break;
        
      case 'pdf':
        content = generatePDF(filteredExpenses);
        mimeType = 'text/html;charset=utf-8;';
        fileExtension = 'html'; // Will open in browser, user can print to PDF
        break;
        
      default:
        throw new Error(`Unsupported format: ${options.format}`);
    }
    
    // Ensure filename has correct extension
    const filename = options.filename.includes('.') 
      ? options.filename 
      : `${options.filename}.${fileExtension}`;
    
    downloadFile(content, filename, mimeType);
    
    return {
      success: true,
      message: `Successfully exported ${filteredExpenses.length} expenses as ${options.format.toUpperCase()}`,
      recordCount: filteredExpenses.length
    };
    
  } catch (error) {
    console.error('Export failed:', error);
    return {
      success: false,
      message: `Export failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
      recordCount: 0
    };
  }
};